name: CI

on:
  push:

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Lilia Repository
        with:
          path: lilia

      - uses: leafo/gh-actions-lua@v8.0.0
        name: Set Up Lua
        with:
          luaVersion: "5.2"

      - uses: leafo/gh-actions-luarocks@v4.0.0
        name: Set Up Luarocks

      - uses: actions/checkout@v3
        name: Pull GluaCheck
        with:
          repository: LiliaFramework/GluaCheck
          path: luacheck

      - name: Build GluaCheck
        working-directory: luacheck
        run: luarocks make

      - name: Run Luacheck Linting
        working-directory: lilia
        run: |
          luacheck . \
            --no-redefined \
            --no-global --no-self \
            --no-max-line-length --no-max-code-line-length \
            --no-max-string-line-length --no-max-comment-line-length \
            --no-max-cyclomatic-complexity